# fly.toml app configuration file generated for redis-personal on 2023-07-29T11:15:18-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "redis-personal"
primary_region = "sea"

[build]
  image = "flyio/redis:6.2.6"

[[mounts]]
  source = "redis_server"
  destination = "/data"

# Uncomment these lines for public internet access to Redis on port 10000
#
# [[services]]
# internal_port = 6379
# protocol      = "tcp"

#   [[services.ports]]
#   port     = "10000"

#   [[services.tcp_checks]]
#   interval = 10000
#   timeout  = 2000
